- ractor/src/actor/actor_cell.rs
- ractor/src/lib.rs
- ractor/src/time/mod.rs
- ractor/src/time/tests.rs
The following standard Erlang functionalities from the time model are added in this PR
1. `send_after`
2. `send_interval`
3. `exit_after`
There are other functionalities but they're not generally related to `ractor`
Blocked on merging #5 first, then rebasing this
> Support for Erlang-style timers.

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- README.md
- ractor-repl/src/main.rs
- ractor-repl/src/ping_pong.rs
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/lib.rs
- ractor/src/port/mod.rs
- ractor/src/rpc/mod.rs
- ractor/src/rpc/tests.rs
- ractor/src/time/mod.rs
Includes struct, trait, and function documentation with inputs + outputs documented. Additionally I've changed the visibility of `Actor::new` and `Actor::start` in favor of `spawn` and `spawn_linked`.
This is because we can now hide the usage of `ActorPortSet` outside of `ractor`
Blocked on #6 and a rebase
> Large code documentation update

- README.md
- ractor/Cargo.toml
- ractor/examples/counter.rs
- ractor/examples/ping_pong.rs
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/lib.rs
- ractor/src/rpc/mod.rs
- ractor/src/rpc/tests.rs
- ractor/src/time/mod.rs
- ractor/src/time/tests.rs
1. Signal will KILL async work
2. Stop will gracefully exit on the next iteration (so async work will complete, but no new messages processed)
Addtionally test coverage around what's stopped vs killed.
Also wired up signal such that a Kill signal will also terminate any supervisor work
Blocked on #7 and a rebase
> Make the stop port separate from signal port so we don't cancel async work on graceful shutdown

- ractor/Cargo.toml
- ractor/examples/supervisor.rs
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/errors.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/lib.rs
- ractor/src/port/mod.rs
- ractor/src/registry/mod.rs
- ractor/src/registry/tests.rs
- ractor/src/rpc/call_result.rs
- ractor/src/rpc/mod.rs
- ractor/src/rpc/tests.rs
- ractor/src/time/mod.rs
This follows the Erlang notion of [name registration via `register_name/3`](https://www.erlang.org/doc/man/global.html#register_name-2).
In our case, it's an in-memory naming, but allows global addressing of actors.
Additionally this PR addresses limitations in the port listening routines which wasn't using priorities due to the random way `tokio::select!` operates by default. Now we add the `biased;` indication to identify that we're handling the fairness of the ports, in that there is an inherent priority in them (Signal > Stop > Supervision > Message).
> Adding support for a global singleton registry for named actors

- ractor-playground/src/ping_pong.rs
- ractor/Cargo.toml
- ractor/examples/counter.rs
- ractor/examples/output_port.rs
- ractor/examples/ping_pong.rs
- ractor/examples/supervisor.rs
- ractor/src/actor/actor_cell/actor_ref.rs
- ractor/src/actor/actor_cell/mod.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/actor_id.rs
- ractor/src/lib.rs
- ractor/src/pg/mod.rs
- ractor/src/pg/tests.rs
- ractor/src/port/output/mod.rs
- ractor/src/port/output/tests.rs
- ractor/src/registry/mod.rs
- ractor/src/registry/tests.rs
- ractor/src/rpc/call_result.rs
- ractor/src/rpc/tests.rs
- ractor/src/time/tests.rs
Erlang's process groups are named groups of collections of actors. They provide easy to use reference material for actors which may have "dispatching" purposes, in that you may want to send to 1, all, a region, etc.
This change also includes making state mutable. We've removed a lot of extra tasks and migrated to using the future's crate `catch_unwind` which saves a lot of state synchronization code laying around.
> Adding PG groups

- README.md
- ractor-playground/src/ping_pong.rs
- ractor/Cargo.toml
- ractor/benches/actor.rs
- ractor/examples/counter.rs
- ractor/examples/monte_carlo.rs
- ractor/examples/output_port.rs
- ractor/examples/philosophers.rs
- ractor/examples/ping_pong.rs
- ractor/examples/supervisor.rs
- ractor/src/actor/actor_cell/actor_properties.rs
- ractor/src/actor/actor_cell/actor_ref.rs
- ractor/src/actor/actor_cell/mod.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/lib.rs
- ractor/src/pg/tests.rs
- ractor/src/port/mod.rs
- ractor/src/port/output/mod.rs
- ractor/src/port/output/tests.rs
- ractor/src/registry/mod.rs
- ractor/src/registry/tests.rs
- ractor/src/rpc/mod.rs
- ractor/src/rpc/tests.rs
- ractor/src/time/mod.rs
- ractor/src/time/tests.rs
This change renames `ActorHandler` to `Actor` and `Actor` to `ActorRuntime`. This is helpful because 90% of what people will work with is just the trait definition, which `Actor` is more logical than the "handler" naming scheme.
Additionally we can avoid existing breakages by re-defining on the `Actor{Handler}` trait the `spawn` and `spawn_linked` calls such that anyone already calling `Actor::spawn` doesn't have to change any syntax.
> Cleanup trait definitions

- ractor/Cargo.toml
- ractor/examples/counter.rs
- ractor/examples/monte_carlo.rs
- ractor/examples/philosophers.rs
- ractor/examples/ping_pong.rs
- ractor/src/macros.rs
- ractor/src/rpc/tests.rs
- ractor/src/time/tests.rs
This PR cleans up the recent addition of macros along with some cleaner matching syntax
1. `call!` - Make an Rpc call without a timeout
2. `call_t!` - Make an Rpc call with a timeout
3. `forward!` - Make an Rpc call and forward it to another actor
4. `cast!` - Cast a message to an actor
There's more to come, but it cleans up the need to build a closure on the fly
> Adding support for RPC macros

- README.md
- ractor/Cargo.toml
- ractor/benches/actor.rs
- ractor/examples/philosophers.rs
- ractor/src/actor/actor_cell/actor_properties.rs
- ractor/src/actor/actor_cell/mod.rs
- ractor/src/actor/errors.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/concurrency.rs
- ractor/src/lib.rs
- ractor/src/macros.rs
- ractor/src/pg/tests.rs
- ractor/src/port/mod.rs
- ractor/src/port/output/mod.rs
- ractor/src/port/output/tests.rs
- ractor/src/registry/tests.rs
- ractor/src/rpc/mod.rs
- ractor/src/rpc/tests.rs
- ractor/src/time/mod.rs
- ractor/src/time/tests.rs
Start moving all the concurrency calls to a common path in order to facilitate moving to multiple runtimes in the future (e.g. `async-std`). However there's more generalization work to do to make that work, this is an initial step and reduces the usage of the `tokio` namespace to just some common patterns used throughout the crate.
> Small macro cleanups + big concurrency cleanup

- README.md
- ractor/Cargo.toml
- ractor/src/actor/actor_cell/mod.rs
- ractor/src/actor/mod.rs
- ractor/src/factory/hash.rs
- ractor/src/factory/job.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/routing_mode.rs
- ractor/src/factory/tests.rs
- ractor/src/factory/worker.rs
- ractor/src/lib.rs
- ractor_cluster/Cargo.toml
- ractor_cluster/src/remote_actor/mod.rs
- ractor_cluster_derive/Cargo.toml
A factory is a manager of a pool of worker processes (actors). The factory is responsible for dispatching messages to this worker pool based on some predefined routing rules. Additionally depending on the routing mode, various internal message queues are supported.
For remote-procedure-calls, workers are expected to reply directly to the caller who submitted the job, rather than replying through the factory.
The factory additionally manages the lifecycle of internal workers, such that the workers are respawned on failure and all but the current `N` processed messages are handled.
> Adding a factory spec which dispatches job to a worker pool

- .github/workflows/integration.yaml
- docker-compose.yml
- ractor/Cargo.toml
- ractor_cluster/Cargo.toml
- ractor_cluster/src/lib.rs
- ractor_cluster/src/node/auth.rs
- ractor_cluster/src/node/mod.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/node/node_session/tests.rs
- ractor_cluster/src/protocol/auth.proto
- ractor_cluster/src/protocol/control.proto
- ractor_cluster_derive/Cargo.toml
- ractor_cluster_integration_tests/envs/auth-handshake.env
- ractor_cluster_integration_tests/envs/dist-connect.env
- ractor_cluster_integration_tests/envs/pg-groups.env
- ractor_cluster_integration_tests/src/repl.rs
- ractor_cluster_integration_tests/src/tests/auth_handshake.rs
- ractor_cluster_integration_tests/src/tests/dist_connect.rs
- ractor_cluster_integration_tests/src/tests/encryption.rs
- ractor_cluster_integration_tests/src/tests/mod.rs
- ractor_cluster_integration_tests/src/tests/pg_groups.rs
- ractor_playground/src/distributed.rs
This change adds support, upon a peer's connection, to list the peer's peers and then try connecting to them.
Integration tests added
```bash
docker compose build
docker compose --env-file ./ractor_cluster_integration_tests/envs/dist-connect.env up --exit-code-from node-c
...
node-c  | [2023-02-20T01:05:18.159Z DEBUG ractor_cluster_integration_tests::tests::dist_connect] Connected session information: [NameMessage { name: "AjNVdQD5zsl97JiGyyme7poAnsGFCk@node-b", flags: Some(NodeFlags { version: 1 }), connection_string: "node-b:8198" }, NameMessage { name: "5yPiX775t9nVOI2WLwDZKLCRrUW7bK@node-a", flags: Some(NodeFlags { version: 1 }), connection_string: "node-a:8199" }]
node-c  | [2023-02-20T01:05:18.160Z INFO  ractor_cluster_integration_tests::tests::dist_connect] Transitive connections …
```
> [cluster] Add support for transitive connections between nodes

- ractor_cluster/README.md
- ractor_cluster/src/macros.rs
- ractor_cluster/src/node/mod.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/remote_actor/mod.rs
- ractor_cluster/src/remote_actor/tests.rs
- ractor_cluster_integration_tests/src/tests/auth_handshake.rs
- ractor_cluster_integration_tests/src/tests/dist_connect.rs
- ractor_cluster_integration_tests/src/tests/encryption.rs
- ractor_cluster_integration_tests/src/tests/pg_groups.rs
- ractor_playground/src/distributed.rs
Additionally this cleans up some syntax for setting up some of the types in `ractor_cluster` but it's all essentially a no-op except a few small constructor calls.
> More tests + documentation

- README.md
- ractor_cluster/README.md
Ractor has a website on github pages which is hosted at 
https://slawlor.github.io/ractor
where general best-practices, quickstarts, and non api-doc information will be hosted
> Add new website link to README(s)

- ractor/Cargo.toml
- ractor/src/actor/actor_cell/actor_ref.rs
- ractor/src/registry/tests.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
Tl;dr; we were checking the wrong type id when resolving an actor from the named registry, it should have been the actor's message type not the full actor type itself.
Test coverage added which fails before the fix
```
failures:
---- registry::tests::test_basic_registation stdout ----
thread 'registry::tests::test_basic_registation' panicked at 'assertion failed: crate::ActorRef::<EmptyActor>::where_is(\"my_actor\".to_string()).is_some()', ractor/src/registry/tests.rs:38:5
```
and is resolved with the fix
```
test result: ok. 56 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.71s
```
Resolves #70
> Oversight when implementing the named registry lookup wrapper in ActorRef

- ractor/Cargo.toml
- ractor/src/actor/actor_cell/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/actor_id.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster_derive/Cargo.toml
1. Hold the worker lifecycle handle for the life of the factory and upon factory shutdown wait for workers to exit too. #85
2. Remove the redundant `get_pid()` call on `ActorId` in favor of `pid()`
> Address some bugs

- ractor/src/actor/actor_cell/actor_properties.rs
- ractor/src/actor/actor_cell/mod.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/concurrency.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/node/node_session/tests.rs
This change adds support for stopping or killing an actor while waiting for the shutdown routine to complete. This is often useful to be assured an actor's shutdown routine has completed before trying to
1. respawn the same actor (potential name clashes/etc)
2. Exiting the process, which may "leak" memory if a thread is still alive without first waiting for proper actor shutdown.
This is often easier than waiting on the `JoinHandle` which is needed to be threaded and shutdown may not be executed by the same process which created/spawned the actor and recorded the `JoinHandle`.
Ideally the `JoinHandle`s wouldn't be necessary, and for ergonomics this would be enough.
Requires that #89 merge first and this be rebased on top of it (should only be last commit).
TODO:
> Add support for "stop and wait" and "kill and wait"

- README.md
- ractor/Cargo.toml
- ractor/src/actor/actor_cell/actor_properties.rs
- ractor/src/actor/actor_cell/actor_ref.rs
- ractor/src/actor/actor_cell/mod.rs
- ractor/src/actor/errors.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor_id.rs
- ractor/src/factory/job.rs
- ractor/src/factory/worker.rs
- ractor/src/lib.rs
- ractor/src/macros.rs
- ractor/src/port/mod.rs
- ractor/src/rpc/mod.rs
- ractor/src/rpc/tests.rs
- ractor/src/tests.rs
- ractor/src/time/mod.rs
- ractor_cluster/Cargo.toml
- ractor_cluster/README.md
- ractor_cluster/src/node/client.rs
- ractor_cluster_derive/Cargo.toml
This PR makes it that send errors don't swallow the error up if they can't send a message to an actor, they will return the message which was unable to be sent in order to facilitate retries/cleaner error handling/etc.
> Capturing send errors better

- README.md
- ractor/Cargo.toml
- ractor/src/actor/actor_cell/actor_ref.rs
- ractor/src/actor/errors.rs
- ractor/src/lib.rs
- ractor/src/message.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This PR adjusts a few trait bounds in `ractor` to
1. Remove the need to implement `Message` on `ActorRef` except for the implementation where it's required. 
2. Add `Sync` manually on `ActorRef` in order to remove the necessity for `Message` to be `Sync`.
The more important change here is point (2) which is helpful because the underlying message type **does not need to be `Sync`**. Because we use channels under the hood, we don't need `Sync` for message types, but `ActorRef` won't then automatically get that trait auto implemented by the compiler because the message type isn't `Sync`.
> Adjust trait bounds

- ractor/src/actor/errors.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/lib.rs
Sometimes the embedded message is not needed and we need to normalize a number of errors from different sources, so add a `map` function which allows `err.map(|_| ())`.
> Add `map` for RactorErr/MessagingErr<T>

- ractor/Cargo.toml
- ractor/src/actor/mod.rs
- ractor/src/concurrency.rs
If `--cfg tokio_unstable` is set in RUSTFLAGS, then allow `--feature tracing`. This enables the task::Builder API, which allows tasks to be named.
We use that here to name them after the actor name, which makes the output in tokio-console much more readable.
> Name tasks if the the unstable tokio tracing feature is enabled.

- ractor/Cargo.toml
- ractor/src/actor/errors.rs
- ractor/src/lib.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This captures the pretty-print (alternate) formatting flag from the parent caller, and propogates it (if necessary) and additionally captures the inner error on a startup panic (if possible).
> Add better formatting of error types which propogates the inner error information (if present)

- ractor/src/factory/mod.rs
- ractor/src/factory/stats.rs
- ractor/src/factory/tests/mod.rs
- ractor/src/factory/tests/worker_lifecycle.rs
- ractor/src/factory/worker.rs
This PR solves a small bug in worker lifecycle management.
**currently** If the factory has a queue of backlogged work, and a worker dies, when it's restarted, it won't immediately dequeue the next message from the factory's queue. It will only get a message on the next incoming factory message which additionally since there's a "free" worker, even with a backlog of work, that incoming message will jump the queue.
This is incorrect behavior, and queue'd message should be served first. This change makes it that when a worker is re-created, it will dequeue a message as the worker is now "free".
Tests added to cover this scenario going forward.
> [factory] Bug in worker lifecycle management

- ractor/Cargo.toml
Without this non-dev builds (ie dependencies) fail:
```
error[E0432]: unresolved import `tokio_primatives`
--> /home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ractor-0.8.4/src/concurrency.rs:139:9
|
139 | pub use tokio_primatives::*;
|         ^^^^^^^^^^^^^^^^ use of undeclared crate or module `tokio_primatives`
error[E0432]: unresolved imports `crate::concurrency::JoinHandle`, `crate::concurrency::MpscReceiver`, `crate::concurrency::MpscUnboundedReceiver`, `crate::concurrency::MpscReceiver`, `crate::concurrency::MpscSender`, `crate::concurrency::MpscUnboundedReceiver`, `crate::concurrency::MpscUnboundedSender`
--> /home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ractor-0.8.4/src/actor/mod.rs:16:5
|
16 | use crate::concurrency::JoinHandle;
| …
```
> Add rt+macro features to tokio dep to fix build

- ractor_cluster/src/lib.rs
- ractor_cluster/src/node/mod.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster_integration_tests/src/tests/auth_handshake.rs
When setting up a node, presently there's no way to capture events on nodes without polling the `NodeServer`.
This change adds a `NodeEventSubscription` trait so that subscribers can implement the trait to get node events.
Additionally integration tests updated to prove subscription events are wired up right
```text
node-a  | [2023-05-19T15:51:28.807Z WARN  ractor_cluster_integration_tests::tests::auth_handshake] [SubscriptionEventLogger] Node 0 (172.19.0.3:38756) opened
node-b  | [2023-05-19T15:51:28.807Z WARN  ractor_cluster_integration_tests::tests::auth_handshake] [SubscriptionEventLogger] Node 0 (172.19.0.2:8199) opened
...
node-b  | [2023-05-19T15:51:28.808Z WARN  ractor_cluster_integration_tests::tests::auth_handshake] [SubscriptionEventLogger] Node 0 (172.19.0.2:8199) …
```
> Add node event subscription

- README.md
- ractor/examples/counter.rs
- ractor/examples/monte_carlo.rs
- ractor/examples/output_port.rs
- ractor/examples/philosophers.rs
- ractor/examples/ping_pong.rs
- ractor/examples/supervisor.rs
- ractor/src/lib.rs
While importing `ractor` into one of my projects, I was trying to re-create the example under `ractor/ractor/examples/supervisor.rs`. However, I was getting an issue around the use of ` #[async_trait::async_trait]` to mark the `impl Actor` for the existing structs. I imagine this didn't come up in development, since the `async_trait` lib is one of the examples. I know for certain libraries, such as `serde`, it's sometimes common to include the `Serialize, Deserialize` traits as re-exported from the base library (sometimes hidden behind a feature flag, if `serde` is optional), which prevents developers from having to manually re-add a second dependency in order to take advantage of it. I've done the same here, which seems to have solved the problem. If you have any questions or would like …
> Add re-export of async_trait

- ractor/examples/monte_carlo.rs
This causes the cast to the parent to not panic, avoiding error messages, and simply error out the child if it can't talk to the parent.
Resolves #162
> Fix monte_carlo example

- ractor/Cargo.toml
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/supervisor.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
> Fix linking bug which causes a stack overflow on a thread when actors are bi-directionally linked

- ractor/src/actor/actor_cell.rs
- ractor/src/actor/actor_ref.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/pg/mod.rs
- ractor/src/registry/pid_registry.rs
`link`ing an actor to another actor, in `ractor`, invokes the parent-child relationship and makes the parent the supervisor of the child. This means if the parent dies, before the child can process a supervision event (in say a doubly-linked scenario), the child will be terminated as part of the parent's exit flow (and not just terminated, but killed halting any async work in any flow). 
This is non-ideal for looser ownership scenarios.
This PR introduces the notion of `monitor`ing (along with `unmonitor` and `clear_monitors`) which allows a non-parent relationship to supervision. This means an actor can monitor another actor without being in the direct lifecycle path yet still receive supervision events.
NOTE: In order to not require the state to implement `Clone`, we instead add a …
> Add monitoring of actors from peers, without full linking support.

- ractor/Cargo.toml
- ractor/src/common_test.rs
- ractor/src/concurrency/async_std_primatives.rs
- ractor/src/concurrency/mod.rs
- ractor/src/factory/tests/mod.rs
- ractor/src/tests.rs
This stabilizes some tests and other functionality which is runtime-specific to async-std runtimes. 
This is merged from the unstable wasm runtime logic where these were fixed as by-products.
> Stabilize async-std runtime

- ractor/src/actor/messages.rs
- ractor/src/lib.rs
- ractor/src/pg/mod.rs
- ractor/src/pg/tests.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/node/node_session/tests.rs
- ractor_cluster/src/protocol/control.proto
Might resolve #31.
I went the proposed route with split functions and `(scope, group)` as an identifying tuple.
Couldn't find the mentioned protobuf OTW cluster protocol changes.
As this is my first-ever PR with 'real' code I suggest a more thorough look. My main concerns besides the API design are:
* correct handling of monitors, and adjacently,
* whether I should handle idempotency of received messages if an `ActorCell` is part of multiple scopes and groups. Couldn't find any mechanisms for the existing process group implementation, so I assume this is not necessary.
Thanks!
--
Edit: Regarding the code coverage: this seems to mostly stem from duplicated yet also previously untested logic due to the split function approach. The exception is the new `which_scopes_and_groups()` for which I …
> Add Erlang-inspired process group (`pg`) scopes

- ractor/Cargo.toml
- ractor/src/pg/tests.rs
This PR adds the crate [serial_test ](https://crates.io/crates/serial_test) to the dev dependencies as suggested in https://github.com/slawlor/ractor/pull/177#discussion_r1390216399.
Based on its functionality, it:
* enables the `which_scopes_and_groups` test, and
* lets it run sequentially to:
*  `test_pg_monitoring`
* `test_scope_monitoring`
--
Curiously, my tests pass when I don't add the `#[serial]` macro to either (but not both) of the monitoring tests.
Maybe their `Actor` implementations for `NotificationMonitor` clash, but my mental model of how this works isn't complete enough yet to figure that one out.
> Fix concurrency for pg monitor tests.

- ractor/src/actor/messages.rs
- ractor/src/actor/tests/mod.rs
Add convenience methods on SupervisionEvent to quickly get the actor the event refers to.
I find myself frequently writing pattern matchers for the `SupervisionEvent` type, such as for tracing or other general supervision event handling. Here is one example from the code base I'm working with:
```rust
impl MyActor {
#[tracing::instrument(skip_all, fields(actor.id = tracing::field::Empty, actor.name_pretty = tracing::field::Empty))]
async fn handle_my_specialized_supervisor_evt(
&self,
myself: ActorRef<MyMessage>,
message: SupervisionEvent,
state: &mut MyState,
) -> Result<(), ActorProcessingErr> {
use SupervisionEvent::*;
if let (ActorPanicked(who, _) | ActorTerminated(who, _, _) | ActorStarted(who)) = &message {
tracing::Span::current()
.record("actor.name_pretty", …
```
> Get Actor references from SupervisionEvent

- ractor/src/actor/mod.rs
Adds text section annotation to actor module docs to fix formatting in docs.rs
before
after
> Fix actor module documentation formatting

- README.md
- ractor/Cargo.toml
> Minimize tokio dependence in async_std runtime and cleanup doc ambiguity

- ractor/src/pg/mod.rs
- ractor/src/pg/tests.rs
Supersedes #189 and introduces an `index` field to the `PgState` struct to map `ScopeName` to `Vec<GroupName>`.
If this isn't what was in mind, I'd need another pointer :)
Would also be open to refactoring the index's value and the modules `Vec<...>`-method returns to `HashSet`s if that makes more sense.
And sorry for the PR noise :)
--
Relating to https://github.com/slawlor/ractor/pull/177#discussion_r1363016547
> This is where having another index might be helpful, i.e. Scope -> Group name in a separate mapping. But that's an optimization that can be added in the future.
and https://github.com/slawlor/ractor/issues/184#issuecomment-1846273238
> I meant another global index linking the scopes to groups. So you could efficiently lookup the groups from a given scope. This would remove some …
> `pg`: Add `ScopeName` -> `Vec<GroupName>` mapping

- ractor/Cargo.toml
- ractor/benches/async_traits.rs
The difference between `async-trait` and the native `async fn` in traits implementation brings in the question of accessing large futures by not boxing them. This benchmark creates 100K u64's on the stack and runs the actor passing around state to be in both scenarios in order to assess the impact of not boxing the futures for performance
**3 Trials, with 50k u64's on the stack**
```
$ cargo bench --bench async_traits -p ractor --no-default-features -F tokio_runtime
Finished bench [optimized] target(s) in 1.57s
Running benches/async_traits.rs (target/release/deps/async_traits-c230612eb7565929)
Gnuplot not found, using plotters backend
Waiting on 50 messages with large data in the Future to be processed
time:   [134.00 µs 135.02 µs 136.16 µs]
change: [+186.13% +189.02% +191.85%] (p = 0.00 …
```
> Benchmark for large futures

- ractor/src/lib.rs
- ractor_cluster/src/lib.rs
It is already being set in CI, so otherwise no changes needed.
https://www.reddit.com/r/rust/comments/f5xpib/psa_denywarnings_is_actively_harmful/
https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html
> fix(lint): don't use deny(warnings) in library, rather use it in ci.

- ractor/src/time/mod.rs
Because `msg` is only invoked at most once, its `Fn` bound could be relaxed to `FnOnce`. In some cases, this would avoid forcing callers to either clone or wrap in an `Arc` the data captured by the message builder closure.
> Relax `Fn` bound to `FnOnce` on the message builder argument to `ractor::time::send_after`

- .github/workflows/ci.yaml
- .github/workflows/integration.yaml
- docker-compose.yml
- ractor/Cargo.toml
- ractor/src/factory/job.rs
- ractor/src/serialization.rs
- ractor_cluster_derive/src/lib.rs
- ractor_cluster_integration_tests/Cargo.toml
- ractor_cluster_integration_tests/Dockerfile
- ractor_cluster_integration_tests/src/ractor_forward_port_tests.rs
- ractor_cluster_integration_tests/src/tests/pg_groups.rs
When working with types in outside crates it quickly becomes a nuisance to implement various wrapper types just to be able to implement BytesConvertable. This becomes especially annoying once one has to interface with an existing codebase that has the original types deeply ingrained.
This PR adds an optional feature called "blanket_serde" which replaces the current default implementations of BytesConvertable with a blanket implementation utilizing serde and pot.
In the process a handful of bugs were found, where tests and BytesConvertable implementations were inconsistent in their Deserialization / Serialization.
For example there were cases of Strings into_bytes() function being used for serialization in combination with <String as BytesConvertable>::from_bytes being used for …
> Serde blanket implementation feature 

- README.md
- ractor/examples/supervisor.rs
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/errors.rs
- ractor/src/factory/factoryimpl.rs
- ractor/src/lib.rs
- ractor/src/tests.rs
- ractor_cluster/src/net/session.rs
- ractor_cluster/src/node/mod.rs
- ractor_cluster/src/node/node_session/mod.rs
Additionally addresses #164 to make errors more consistent.
Resolves #164
> Prep for 0.10.0 release

- ractor/Cargo.toml
- ractor/src/actor/mod.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/factory/job.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
Handling actor startup errors in `pre_start` results in a `SpawnErr` however it wasn't being handled putting the actor into a `Stopped` state (which it should have), since that's where the actor registries are cleaned up such as the named and `pg` registries. This would result in dangling references in those registries.
This PR specifically captures spawn failures and sets the actor to stopped to call the necessary de-registration hooks.
Resolves #240
> Adding handling if the actor fails during pre_start that it doesn't poison the named and pid registries.

- README.md
Since we continue to use `async_trait` in default mode, we should keep it in the demo code, otherwise, newcomers will meet the same issue in: https://github.com/slawlor/ractor/issues/217, that's the problem I ran into now.
> Fix sample code in readme

- ractor/Cargo.toml
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/concurrency/tokio_primatives.rs
- ractor/src/factory/factoryimpl.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/queues.rs
- ractor/src/lib.rs
- ractor/src/macros.rs
- ractor/src/port/output/mod.rs
- ractor/src/rpc/mod.rs
- ractor/src/time/mod.rs
- ractor_cluster/Cargo.toml
- ractor_cluster/src/node/mod.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/remote_actor/mod.rs
- ractor_cluster_derive/Cargo.toml
We should only notify the stop listener AFTER `post_stop`  has executed, which is when the state gets set to `Stopped`
Closes #254
A new test has been added called `actor_post_stop_executed_before_stop_and_wait_returns`. Before the fix it fails with
```
---- actor::tests::actor_post_stop_executed_before_stop_and_wait_returns stdout ----
2024-09-13T15:47:34.344047Z TRACE actor_post_stop_executed_before_stop_and_wait_returns:Actor{id="0.0"}: ractor::actor: Actor Local(0) stopped with no reason
thread 'actor::tests::actor_post_stop_executed_before_stop_and_wait_returns' panicked at ractor/src/actor/tests/mod.rs:1040:5:
assertion `left == right` failed
left: 1
right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures: …
```
> We should only notify the stop listener AFTER `post_stop` 

- ractor/Cargo.toml
- ractor/src/actor/actor_properties.rs
- ractor/src/concurrency/mod.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This change further reduces the memory utilization of the actors, down to ~ 13KB. However it also has the added benefit that some benchmarks are showing additional wins in message processing latencies.
```
Benchmarking Waiting on 100 actors to process first message: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.5s, enable flat sampling, or reduce sample count to 60.
Waiting on 100 actors to process first message
time:   [804.50 µs 818.01 µs 833.69 µs]
change: [-34.074% -26.977% -21.803%] (p = 0.00 < 0.05)
Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
3 (3.00%) high mild
1 (1.00%) high severe
Waiting on 1000 actors to process first message
time:   [9.6242 ms 9.7702 ms 9.9224 ms]
change: …
```
> More memory improvements, but smaller. No API changes

- .github/workflows/coverage.yml
- ractor/Cargo.toml
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/actor_properties.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
Before
```
9.82 real         4.19 user         3.78 sys
1353138176  maximum resident set size
0  average shared memory size
0  average unshared data size
0  average unshared stack size
90426  page reclaims
3  page faults
0  swaps
0  block input operations
0  block output operations
0  messages sent
0  messages received
0  signals received
1870  voluntary context switches
524687  involuntary context switches
40331547246  instructions retired
23204316450  cycles elapsed
1351667776  peak memory footprint
```
After:
```
6.29 real         2.73 user         2.32 sys
1121075200  maximum resident set size
0  average shared memory size
0  average unshared data size
0  average unshared stack size
76399  page reclaims
3  page faults
0  swaps
0  block input operations
0  block output operations
0 …
```
> Move to oneshot's instead of bounded channels of size 1

- ractor/Cargo.toml
- ractor/src/factory/factoryimpl.rs
- ractor/src/factory/job.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/stats.rs
- ractor/src/factory/tests/basic.rs
- ractor/src/factory/tests/draining_requests.rs
- ractor/src/factory/tests/dynamic_discarding.rs
- ractor/src/factory/tests/dynamic_pool.rs
- ractor/src/factory/tests/lifecycle.rs
- ractor/src/factory/tests/priority_queueing.rs
- ractor/src/factory/tests/worker_lifecycle.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster_derive/Cargo.toml
This patch adds a generic stats layer trait that can be implemented to provide whatever custom statistics collection medium downstream use-cases prefer.
Dynamic dispatch is utilized since we're going to use an `Arc` anyways and given the likelihood of a single implementation, LLVM will likely inline the type anyways. This saves the added generic overhead.
> Generic stats impl for factories

- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/node/node_session/tests.rs
Currently remote actors are always joined into the default process group.
This patch properly joins them into the scoped groups that are transmitted by the remote node.
> fix issue where remote actors in PG's were always joined into the default scope locally

- ractor/src/actor/actor_cell.rs
- ractor/src/actor/actor_properties.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/factory/mod.rs
This is done by multiplexing the low-pri messaging port and when an internal draining message is received, we've emptied the actor's queue and can shut down.
Test coverage added.
> Add support for draining an actor's message queue.

- ractor/Cargo.toml
- ractor/src/factory/queues.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
We were calculating the number of removed queue items in reverse leading to an underflow on a `usize`. 
Also added test coverage on queueing implementations.
> Adding tests for queueing and fix bug in queue length calculation

- ractor/Cargo.toml
- ractor/src/factory/factoryimpl.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster/README.md
- ractor_cluster_derive/Cargo.toml
Some stat collection was lost in merging various branches. This fixes a fix on another branch that was an oversight and should have been collected stats (right now they'll report 0).
> Missing callsites for a bunch of factory stats

- ractor/Cargo.toml
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/actor_properties.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/factory/discard.rs
- ractor/src/factory/factoryimpl.rs
- ractor/src/factory/job.rs
- ractor/src/factory/lifecycle.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/queues.rs
- ractor/src/factory/routing.rs
- ractor/src/factory/tests/dynamic_discarding.rs
- ractor/src/factory/tests/dynamic_pool.rs
- ractor/src/factory/tests/lifecycle.rs
- ractor/src/factory/tests/worker_lifecycle.rs
- ractor/src/factory/worker.rs
- ractor/src/lib.rs
- ractor/src/message.rs
- ractor/src/pg/mod.rs
- ractor/src/port/output/mod.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This pull request adds a few things.
1. I'm enabling a lot more warning messages on the core `ractor` crate in order to maintain a higher code quality. This induced a lot of needlessly `pub` functions to be marked as `pub(crate)` since the visibility was controlled by the parent struct anyways. Additionally a lot of `Debug` implementations are added for publicly exported types.
2. This adds a new type called `RetriableMessage` which when used in conjunction with a `Factory` allows us to automatically retry a message should it be dropped due to a factory worker failing (or panicking). Tests added on this functionality.
3. Lastly as requested in #272 and #248, with the stabilization of async traits natively, factories were gated behind the `async-trait` feature since we utilized `dyn Trait` …
> Add silent-retry support for factory messages + support for factories without `async-trait`

- ractor/Cargo.toml
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/actor_properties.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This patch does 2 things
1. Adds ability to access the type id and runtime check the message type of an `ActorCell`. RE: #276
2. Adds ability to stop & drain children actors, by traversing the supervision tree, instead of requiring users to hold the handles themselves in the states. RE: #226
> Add child operations from supervision tree AND type_id support

- ractor/Cargo.toml
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/actor_id.rs
- ractor/src/actor/actor_ref.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/factory/factoryimpl.rs
- ractor/src/factory/job.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/queues.rs
- ractor/src/factory/tests/basic.rs
- ractor/src/factory/tests/draining_requests.rs
- ractor/src/factory/tests/dynamic_discarding.rs
- ractor/src/factory/tests/dynamic_pool.rs
- ractor/src/factory/tests/lifecycle.rs
- ractor/src/factory/tests/priority_queueing.rs
- ractor/src/factory/tests/worker_lifecycle.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
1. [COMPAT BREAK] Switch to `bon::Builder` for factory arguments and settings which gives compile-time, vs run-time, safety constructing types.
2. Cleanup a lot of debug impl's
3. Cleanup comments in various places.
And bump the version to 0.13.0 because of the migration to bon
> Large cleanup

- ractor/Cargo.toml
This addresses issue #285. I went over ractor's dependencies and bumped them where the minimum required version didn't match actual use in code - e.g. use of `JoinSet::join_all` that was only introduced in tokio 1.40.0.
This change is non-breaking - a project that uses ractor and successfully builds must already use versions of tokio/bon at least as recent as these bumped versions.
> Bump ractor dependencies to match their actual use (#285)

- ractor/src/actor/actor_cell.rs
- ractor/src/actor/tests/supervisor.rs
There is an additional i in the get supervisor method which is not an issue but it's not correct.
> fix: get supervisor method typo

- .github/workflows/ci.yaml
- ractor/Cargo.toml
- ractor/src/message.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
> Gate the span propagation with a feature so it can be opted-out

- ractor/Cargo.toml
- ractor/src/factory/job.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/queues.rs
- ractor/src/factory/tests/basic.rs
- ractor/src/factory/tests/dynamic_pool.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
With #266, automation span propagation was added to `ractor`. This is very helpful in tracing context through actors, such that contextual information can be persisted through a message's lifecycle. 
However, in factories, this is more subtle due to (a) internal queueing and (b) the worker's requirement to interface with the Factory directly (for ping/pong heartbeats). 
Consider a message sent to a factory, which is a `Job`. When the job is picked up, the factory's message handler `handle()` will be instrumented with the span included in the message, silently by the framework for you. However should the factory choose to queue the message, then once that iteration of `handle()` is completed, the span context is lost. Then the factory may utilize a future message event to dequeue that …
> Add proper span handling to factories through extension trait

- .github/workflows/ci.yaml
- ractor/Cargo.toml
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
> Fix broken build for non async-trait builds

- ractor/Cargo.toml
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/actor_properties.rs
- ractor/src/actor/tests/mod.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This allows someone to wait for the actor's exit without waiting on the JoinHandle
Resolves #303
> Add a `wait()` operator for an actor

- .github/workflows/ci.yaml
- .github/workflows/integration.yaml
- ractor/Cargo.toml
- ractor/src/actor/mod.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/factory/job.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster/src/lib.rs
- ractor_cluster/src/net/listener.rs
- ractor_cluster/src/net/session.rs
- ractor_cluster/src/node/mod.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/node/node_session/tests.rs
- ractor_cluster/src/remote_actor/mod.rs
- ractor_cluster/src/remote_actor/tests.rs
- ractor_cluster_integration_tests/Cargo.toml
- ractor_cluster_integration_tests/src/tests/pg_groups.rs
- ractor_playground/src/distributed.rs
- ractor_playground/src/ping_pong.rs
Resolves #309 
This is really a no-op change except assuring that all of the test coverage runs for both `async-trait` and no-`async-trait` usages.
> Expose async-trait to  as a feature which can be enabled or disabled selectively

- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/supervisor.rs
This fixes #310 
Please suggest where and what tests I can add.
> fix: get_children should not break supervision tree integrity

- .github/workflows/ci.yaml
- README.md
- ractor/Cargo.toml
- ractor/src/actor/actor_cell.rs
- ractor/src/actor/messages.rs
- ractor/src/actor/mod.rs
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/lib.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This PR re-adds the monitor API, but with an option in the map to save allocations when unused.
Additionally we move to Option<HashMap> types to save on allocations for regular supervisions (if the actor doesn't supervise anything, we don't need to create the empty map)
This was originally removed in #260 to save on memory, but it was used by the community and therefore a valuable API as noted in #307
TBD mem measurement
> Add monitor API back

- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/node/node_session/tests.rs
Time drift happens and time going backwards is common on NTP enabled servers. When time drift happens it's not worth it to kill the node session.
Change the timestamp payload to use duration against NodeSession specific Instant epoch initialized at creation time. This ensures the timestamp increases monotonically. It can only go backwards when the payload is malformed.
Note - this makes the timestamp in the payload an offset from UNIX_EPOCH. I think it is fine and nobody should be reading the timestamp for anything useful.
> Make latency measurement in ping message robust against time drift

- ractor/Cargo.toml
- ractor/src/actor/derived_actor.rs
- ractor/src/factory/factoryimpl.rs
- ractor/src/rpc/mod.rs
- ractor/src/time/mod.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This PR also adds equivalent exposure to DerivedActorRef that is available on ActorRef
> Marking that the converter function in the derived actor is cross-thread safe since it's just an Into() call.

- ractor_cluster/src/node/mod.rs
- ractor_cluster/src/node/node_session/mod.rs
- ractor_cluster/src/node/node_session/tests.rs
- ractor_cluster/src/protocol/control.proto
- ractor_cluster_integration_tests/src/tests/pg_groups.rs
Remote actors and PG memberships are sync after authentication are done. This new message can be used to query the state of this initial sync. The session setup is complete once the query returns true.
This address the race condition found in #319
> Add a new NodeSessionMessage to get the state of initial sync

- ractor_cluster/src/net/session.rs
Each of NodeSession's message is encoded with a 2 bytes length prefix followed by the actual object data. Originally when writing the message to TcpStream we write them separately, however the TcpStream is not buffered, so the first 2 bytes write may be pushed to the underlying network stack as a tiny packet, then the data is pushed as one or more packets.
The first tiny packet might trigger the pathological interaction between Nagle's Algorithm and Delayed Acknowledgement in TCP, causing from 40ms to 200ms delay of the actual payload delivery. This can be observed from the average 40ms latency between two nodes on the same host conneting via the loopback interface.
Combine the length prefix and payload data to one write_all call to avoid this latency anomaly. Since the message is already …
> Improve NodeSession TCP performance

- .github/workflows/ci.yaml
- ractor/Cargo.toml
- ractor/src/actor/supervision.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/concurrency/async_std_primitives.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
> Fix async-std and re-enable Ci for async-std builds

- ractor/src/actor/actor_cell.rs
- ractor/src/actor/tests/mod.rs
- ractor/src/actor/tests/supervisor.rs
- ractor/src/lib.rs
- ractor/src/registry/tests.rs
Utilities added on
* The ActorRef for spawning children (instance method of `spawn_linked`) 
* The crate root for spawning unmanaged actors
Tests updated to cover functionality.
> Add utility functions for spawning actors

- ractor_cluster/src/net/listener.rs
Or perhaps this should be configurable? For example it can take a `Into<SocketAddr>`
> Bind to [::] to listen for both IPv4 and IPv6 connection

- README.md
- ractor/Cargo.toml
- ractor/src/factory/discard.rs
- ractor/src/factory/factoryimpl.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/ratelim.rs
- ractor/src/factory/routing.rs
- ractor/src/factory/stats.rs
- ractor/src/factory/tests/mod.rs
- ractor/src/factory/tests/ratelim.rs
- ractor/src/lib.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
To be used in all routing decisions so we can centralize future handling logic related to rate limiting.
The goal is to add a general rate limiting offering which can be used at the routing layer, right before sending the job to a worker.
Additionally this adds a new result from routing operations, which denotes that a job isn't accepted but rater rate limited and should be loadshed.
This is a major version break as the API for `Router` will change with added fields and an additional return type.
Lastly this adds a basic leaky-bucket rate limiter which can manage the throughput of the factory based on the leaky bucket algo.
> Generalize the factory routing product & add rate limiting support

- ractor/Cargo.toml
- ractor/src/factory/factoryimpl.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
I missed an edge condition when we're ratelimiting that we might no longer respect routing protocols
This change continually retries the routing stack when routing to a worker which just finished a job, for each queue'd message, until either
1. We route a message
2. We flush the queue
this shouldn't impact anyone not using rate limiting as the rate limit result is impossible from the normal routing protocols.
> Fix ratelimiting introduced edge condition

- ractor/Cargo.toml
- ractor/src/factory/discard.rs
- ractor/src/factory/factoryimpl.rs
- ractor/src/factory/mod.rs
- ractor/src/factory/tests/dynamic_settings.rs
- ractor/src/factory/tests/mod.rs
- ractor/src/factory/worker.rs
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
This allows someone to say reload configeration settings, and internally tear-down and rebuild the factory without fully shutting down and restarting.
Some settings are not dynamically settable without tearing down and rebuilding the factory, unless we want to introduce more strong-types to the message type. This includes, unfortunately, the worker builder, queue, and router.
For settings on those two, there are two choices. (1) tear down and rebuild the factory or (2) thread in dynamic settings to your router and/or queue protocols such that they can internally change their functionality.
> Add ability for a factory's internal state to be updated dynamically

- ractor_cluster/src/net/listener.rs
- ractor_cluster/src/node/mod.rs
- ractor_cluster_integration_tests/Dockerfile
- ractor_cluster_integration_tests/envs/dist-connect.env
- ractor_cluster_integration_tests/src/tests/dist_connect.rs
See Issue #334.
**TLDR:**
Creating a NodeServer with port 0 lets the OS choose an available port. The port chosen by the OS is not reflected in the connection_string. Transitive connections to nodes that used port 0 will fail, since other nodes will try to connect to port 0.
I fixed the issue with the following changes:
- Add a new `NodeServerMessage::PortChanged` that tells the NodeServer to update its connection_string.
- In `net::listener::Listener::post_start()` query the port that the listener is bound to. If it differs from the user-specified port, send the supervisor (the NodeServer) a `PortChanged` Message.
I also changed the input for the dist_connect integration test slightly to use port 0 so that both the basic functionality and this 'edge case' are tested.
---
I'm not entirely …
> Support dynamic NodeServer port allocation

- ractor/Cargo.toml
- ractor_cluster/Cargo.toml
- ractor_cluster_derive/Cargo.toml
Semver compat checked with `cargo semver-checks --default-features` which identified that the MaybeSend bound didn't induce a semver break.
> Bump crate versions for next release prep

- ractor/src/concurrency/mod.rs
- ractor/src/rpc/mod.rs
- ractor_cluster/src/node/mod.rs
This change addresses #343 
Here we will immediately trigger the message send, deferring the receive future. In the previous version, even the send will wait for the caller to poll the future, which means the "send" may not occur right away, and this is somewhat counter intuitive.
> Send call request without requiring await

- .github/wasm-test-runner/.gitignore
- .github/wasm-test-runner/index.js
- .github/wasm-test-runner/package-lock.json
- .github/wasm-test-runner/package.json
- .github/workflows/wasm.yaml
- ractor/src/tests.rs
This PR adds a test runner (.github/wasm-test-runner) to execute unit-tests for wasm32-unknown-unknown in browser, since headless tests execution by wasm-pack is broken.
> update: use xvfb and headful browser to execute unit tests for wasm32-unknown-unknown
